INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (1, 0, 1, 'Index', 'fa-bar-chart', '/', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (2, 0, 2, 'Admin', 'fa-tasks', '', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (3, 2, 3, 'Users', 'fa-users', 'auth/users', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (4, 2, 4, 'Roles', 'fa-user', 'auth/roles', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (5, 2, 5, 'Permission', 'fa-user', 'auth/permissions', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (6, 2, 6, 'Menu', 'fa-bars', 'auth/menu', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (7, 2, 7, 'Operation log', 'fa-history', 'auth/logs', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (8, 0, 8, 'Helpers', 'fa-gears', '', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (9, 8, 9, 'Scaffold', 'fa-keyboard-o', 'helpers/scaffold', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (10, 8, 10, 'Database terminal', 'fa-database', 'helpers/terminal/database', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (11, 8, 11, 'Laravel artisan', 'fa-terminal', 'helpers/terminal/artisan', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (12, 0, 0, 'Affiliates', 'fa-users', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (13, 0, 0, 'SIGs', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (14, 0, 0, 'Events', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (15, 12, 0, 'Add', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (16, 12, 0, 'Index', 'fa-bars', 'affiliates', null, '2017-08-16 14:39:49');
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (17, 12, 0, 'Group By', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (18, 13, 0, 'Add', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (19, 13, 0, 'Index', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (20, 13, 0, 'Group By', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (21, 14, 0, 'Add', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (22, 14, 0, 'Index', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (23, 14, 0, 'Group By', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (24, 17, 0, 'Ethnicity', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (25, 17, 0, 'Is Stem', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (26, 17, 0, 'Year of School', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (27, 17, 0, 'Academic Career', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (28, 17, 0, 'Student Type', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (29, 17, 0, 'Affiliate Type', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (30, 17, 0, 'School (experimental)', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (31, 23, 0, 'Type', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (32, 23, 0, 'Topic', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (33, 23, 0, 'Year', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (34, 23, 0, 'Month', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (35, 23, 0, 'Attendance', 'fa-bars', '#', null, null);
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (36, 15, 0, 'Alumni', 'fa-bars', 'alumni/create', '2017-08-16 13:50:13', '2017-08-16 19:43:35');
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (37, 15, 0, 'Students', 'fa-bars', '*', '2017-08-16 13:50:40', '2017-08-16 13:50:40');
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (38, 15, 0, 'Faculties', 'fa-bars', '*', '2017-08-16 13:51:02', '2017-08-16 13:51:02');
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (39, 15, 0, 'Staff', 'fa-bars', '*', '2017-08-16 13:51:41', '2017-08-16 13:51:41');
INSERT INTO cewit_iis.admin_menu (id, parent_id, `order`, title, icon, uri, created_at, updated_at) VALUES (40, 12, 0, 'add affiliate', 'fa-bars', 'affiliates/create', '2017-08-16 20:02:30', '2017-08-16 20:03:48');